//! Durable, permissioned agent-to-agent work. Delivery is an authenticated pull inbox.
use super::*;
use axum::http::StatusCode;
use axum::{
    Json, Router,
    extract::{Path, Query, State},
    routing::{get, post},
};
use sha2::{Digest, Sha256};

type Api<T> = std::result::Result<Json<T>, http::Error>;
const LEASE_SECONDS: i64 = 300;
const DEFAULT_TIMEOUT_SECONDS: i64 = 86_400;
const MIN_TIMEOUT_SECONDS: i64 = 60;
const MAX_TIMEOUT_SECONDS: i64 = 604_800;
const RESULT_DELIVERY_SECONDS: i64 = 604_800;
#[derive(Debug)]
pub(super) struct HandoffError {
    pub status: StatusCode,
    pub message: &'static str,
}
impl std::fmt::Display for HandoffError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.message)
    }
}
impl std::error::Error for HandoffError {}
fn conflict(message: &'static str) -> anyhow::Error {
    HandoffError {
        status: StatusCode::CONFLICT,
        message,
    }
    .into()
}
fn forbidden(message: &'static str) -> anyhow::Error {
    HandoffError {
        status: StatusCode::FORBIDDEN,
        message,
    }
    .into()
}
fn missing() -> anyhow::Error {
    HandoffError {
        status: StatusCode::NOT_FOUND,
        message: "Task not found",
    }
    .into()
}

#[derive(Debug, Clone, Serialize, FromRow)]
pub(super) struct Handoff {
    pub cursor: i64,
    pub id: String,
    pub request_id: String,
    pub sender_id: String,
    pub sender_name: String,
    pub recipient_id: String,
    pub recipient_name: String,
    pub title: String,
    pub instructions: String,
    pub status: String,
    pub result: Option<String>,
    pub error: Option<String>,
    pub result_acknowledged_at: Option<String>,
    #[serde(skip_serializing)]
    #[sqlx(rename = "claim_hash")]
    _claim_hash: Option<String>,
    pub lease_until: Option<i64>,
    pub timeout_seconds: Option<i64>,
    pub expires_at: Option<i64>,
    pub delivery_mode: String,
    pub sender_binding_generation: Option<i64>,
    pub recipient_binding_generation: Option<i64>,
    pub created_at: String,
    pub updated_at: String,
    pub revision: i64,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct CreateHandoff {
    /// Stable UUID; reuse it for retries of the same task.
    pub request_id: String,
    /// Stable ID from list_agents; the owner must permit this sender to assign work to it.
    pub recipient_id: String,
    pub title: String,
    pub instructions: String,
    /// Maximum lifetime in seconds, from creation through completion. Defaults to 24 hours; range 60 seconds to 7 days.
    pub timeout_seconds: Option<i64>,
    /// Request automatic native delivery. Requires current verified receiver bindings
    /// for both agents; omitted/false preserves the existing pull inbox.
    #[serde(default)]
    pub automatic_delivery: bool,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct ClaimInput {
    /// Random UUID generated by the recipient. Reuse for lost claim responses and renew/complete/fail.
    pub claim_token: String,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct FinishInput {
    pub claim_token: String,
    /// Result for completion, explanation for failure.
    pub message: String,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct TaskClaim {
    pub id: String,
    pub claim_token: String,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct TaskFinish {
    pub id: String,
    pub claim_token: String,
    pub message: String,
}
#[derive(Deserialize)]
struct ListQuery {
    status: Option<String>,
    before: Option<i64>,
}
#[derive(Deserialize)]
struct HistoryQuery {
    after: Option<i64>,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct ListHandoffs {
    pub status: Option<String>,
    /// Cursor returned in next by the previous page.
    pub before: Option<i64>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct GrantInput {
    recipient_id: String,
    enabled: bool,
}

pub(super) fn admin_routes() -> Router<Publisher> {
    Router::new()
        .route("/api/agent-handoff-grants", get(all_grants))
        .route(
            "/api/agent-handoff-grants/{sender_id}",
            get(grants).post(set_grant),
        )
        .route("/api/agent-handoffs", get(owner_list))
        .route("/api/agent-handoffs/{id}", get(owner_get))
        .route("/api/agent-handoffs/{id}/history", get(owner_history))
}
pub(super) fn agent_routes() -> Router<Publisher> {
    Router::new()
        .route("/v1/agents", get(agents))
        .route("/v1/agent-tasks", get(list).post(create))
        .route("/v1/agent-tasks/{id}", get(read))
        .route("/v1/agent-tasks/{id}/claim", post(claim))
        .route("/v1/agent-tasks/{id}/renew", post(renew))
        .route("/v1/agent-tasks/{id}/complete", post(complete))
        .route("/v1/agent-tasks/{id}/fail", post(fail))
        .route("/v1/agent-tasks/{id}/cancel", post(cancel))
        .route("/v1/agent-tasks/{id}/ack-result", post(ack_result))
}
fn valid_text(value: &str, max: usize) -> bool {
    !value.trim().is_empty()
        && value.len() <= max
        && !value
            .chars()
            .any(|c| c.is_control() && c != '\n' && c != '\t')
}
fn claim_digest(token: &str) -> String {
    format!("{:x}", Sha256::digest(token.as_bytes()))
}

impl Publisher {
    pub(super) async fn handoff_deadline_worker(&self) {
        let mut interval = tokio::time::interval(Duration::from_secs(5));
        loop {
            tokio::select! {
                _ = self.0.shutdown.cancelled() => return,
                _ = interval.tick() => {
                    if let Err(error) = self.expire_handoffs().await {
                        tracing::error!(%error, "Could not expire agent handoffs");
                    }
                }
            }
        }
    }
    pub(super) async fn discover_agents(&self) -> Result<Value> {
        let rows: Vec<(String, String, String)> = sqlx::query_as(
            "SELECT c.id,c.name,c.product FROM agent_handoff_grants g JOIN agent_connections c ON c.id=g.recipient_id WHERE g.sender_id=? AND c.disconnected=0 ORDER BY c.name,c.id")
            .bind(self.connection_id()).fetch_all(&self.0.db).await?;
        Ok(json!(rows.into_iter().map(|(id,name,product)| json!({"id":id,"name":name,"product":product,"delivery":"inbox"})).collect::<Vec<_>>()))
    }
    pub(super) async fn create_handoff(&self, input: CreateHandoff) -> Result<Value> {
        Uuid::parse_str(&input.request_id)?;
        if !valid_text(&input.title, 200) || !valid_text(&input.instructions, 16_000) {
            bail!("Task title or instructions are empty or too long");
        }
        let timeout = input.timeout_seconds.unwrap_or(DEFAULT_TIMEOUT_SECONDS);
        if !(MIN_TIMEOUT_SECONDS..=MAX_TIMEOUT_SECONDS).contains(&timeout) {
            bail!("timeout_seconds must be between 60 and 604800");
        }
        if self.connection_id() == input.recipient_id {
            bail!("Choose another agent");
        }
        self.expire_handoffs().await?;
        let _guard = self.0.mutation.lock().await;
        let mut tx = self.0.db.begin().await?;
        if let Some(existing) = sqlx::query_as::<_, Handoff>(
            "SELECT rowid AS cursor,* FROM agent_handoffs WHERE sender_id=? AND request_id=?",
        )
        .bind(self.connection_id())
        .bind(&input.request_id)
        .fetch_optional(&mut *tx)
        .await?
        {
            if existing.recipient_id != input.recipient_id
                || existing.title != input.title
                || existing.instructions != input.instructions
                || (existing.timeout_seconds.is_some() && existing.timeout_seconds != Some(timeout))
                || (existing.timeout_seconds.is_none() && input.timeout_seconds.is_some())
                || (existing.delivery_mode == "automatic") != input.automatic_delivery
            {
                return Err(conflict("request_id already belongs to a different task"));
            }
            return Ok(serde_json::to_value(existing)?);
        }
        let sender: (String,) =
            sqlx::query_as("SELECT name FROM agent_connections WHERE id=? AND disconnected=0")
                .bind(self.connection_id())
                .fetch_one(&mut *tx)
                .await?;
        let recipient: Option<(String,)> = sqlx::query_as(
            "SELECT c.name FROM agent_handoff_grants g JOIN agent_connections c ON c.id=g.recipient_id WHERE g.sender_id=? AND g.recipient_id=? AND c.disconnected=0")
            .bind(self.connection_id()).bind(&input.recipient_id).fetch_optional(&mut *tx).await?;
        let recipient =
            recipient.ok_or_else(|| forbidden("Recipient is not available or permitted"))?;
        let binding_generations = if input.automatic_delivery {
            let generations: Vec<(String, i64)> = sqlx::query_as(
                "SELECT b.connection_id,b.generation FROM handoff_receiver_bindings b JOIN agent_connections c ON c.id=b.connection_id WHERE b.connection_id IN (?,?) AND b.enabled=1 AND b.verified_at IS NOT NULL AND b.proof_expires_at>unixepoch() AND c.disconnected=0",
            )
            .bind(self.connection_id())
            .bind(&input.recipient_id)
            .fetch_all(&mut *tx)
            .await?;
            if generations.len() != 2 {
                return Err(conflict("Automatic handoff receiver is unavailable"));
            }
            let sender_generation = generations
                .iter()
                .find(|(id, _)| id == self.connection_id())
                .map(|(_, generation)| *generation)
                .ok_or_else(|| conflict("Automatic handoff sender is unavailable"))?;
            let recipient_generation = generations
                .iter()
                .find(|(id, _)| id == &input.recipient_id)
                .map(|(_, generation)| *generation)
                .ok_or_else(|| conflict("Automatic handoff receiver is unavailable"))?;
            Some((sender_generation, recipient_generation))
        } else {
            None
        };
        let id = Uuid::new_v4().to_string();
        sqlx::query("INSERT INTO agent_handoffs(id,request_id,sender_id,sender_name,recipient_id,recipient_name,title,instructions,timeout_seconds,expires_at,delivery_mode,sender_binding_generation,recipient_binding_generation) VALUES(?,?,?,?,?,?,?,?,?,unixepoch()+?,?,?,?)")
            .bind(&id).bind(&input.request_id).bind(self.connection_id()).bind(sender.0)
            .bind(&input.recipient_id).bind(recipient.0).bind(&input.title).bind(&input.instructions)
            .bind(timeout).bind(timeout)
            .bind(if input.automatic_delivery { "automatic" } else { "pull" })
            .bind(binding_generations.map(|(sender, _)| sender))
            .bind(binding_generations.map(|(_, recipient)| recipient))
            .execute(&mut *tx).await?;
        let row = Self::handoff_in_tx(&mut tx, &id).await?;
        Self::handoff_event(&mut tx, &row, "created").await?;
        if let Some((_, recipient_generation)) = binding_generations {
            Self::handoff_delivery(
                &mut tx,
                &row,
                "task_offered",
                &row.recipient_id,
                recipient_generation,
            )
            .await?;
        }
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
    async fn handoff_in_tx(tx: &mut Transaction<'_, Sqlite>, id: &str) -> Result<Handoff> {
        Ok(
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE id=?")
                .bind(id)
                .fetch_one(&mut **tx)
                .await?,
        )
    }
    async fn handoff_event(
        tx: &mut Transaction<'_, Sqlite>,
        row: &Handoff,
        action: &str,
    ) -> Result<()> {
        let mut payload = serde_json::to_value(row)?;
        payload["action"] = json!(action);
        sqlx::query("INSERT INTO events(kind,payload) VALUES('agent.handoff',?)")
            .bind(payload.to_string())
            .execute(&mut **tx)
            .await?;
        Ok(())
    }
    async fn handoff_delivery(
        tx: &mut Transaction<'_, Sqlite>,
        row: &Handoff,
        kind: &str,
        connection_id: &str,
        generation: i64,
    ) -> Result<()> {
        let expires_at = if kind == "task_offered" {
            row.expires_at
                .ok_or_else(|| conflict("Automatic task has no deadline"))?
        } else {
            // Return delivery has its own finite window after the task becomes terminal.
            sqlx::query_scalar::<_, i64>("SELECT unixepoch()+?")
                .bind(RESULT_DELIVERY_SECONDS)
                .fetch_one(&mut **tx)
                .await?
        };
        sqlx::query("INSERT INTO handoff_delivery_outbox(id,task_id,kind,connection_id,binding_generation,expires_at) VALUES(?,?,?,?,?,?)")
            .bind(Uuid::new_v4().to_string()).bind(&row.id).bind(kind).bind(connection_id)
            .bind(generation).bind(expires_at).execute(&mut **tx).await?;
        Ok(())
    }
    async fn enqueue_result_delivery(
        tx: &mut Transaction<'_, Sqlite>,
        row: &Handoff,
    ) -> Result<()> {
        if row.delivery_mode == "automatic" {
            let generation = row
                .sender_binding_generation
                .ok_or_else(|| conflict("Automatic task has no sender binding"))?;
            Self::handoff_delivery(tx, row, "result_available", &row.sender_id, generation).await?;
        }
        Ok(())
    }
    /// Materialize elapsed deadlines in the same transaction as their audit events.
    /// Called by the independent sweeper and before reads; late writes are fenced in SQL.
    pub(super) async fn expire_handoffs(&self) -> Result<usize> {
        let mut total = 0;
        loop {
            let mut tx = self.0.db.begin().await?;
            // The first statement writes, avoiding a deferred read transaction that
            // could become a stale SQLite snapshot under concurrent API traffic.
            let ids: Vec<String> = sqlx::query_scalar("UPDATE agent_handoffs SET status='timed_out',error=CASE WHEN status='queued' THEN 'Recipient did not claim the task before its deadline.' ELSE 'Task deadline passed after claim; external effects may be unknown.' END,claim_hash=NULL,lease_until=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id IN (SELECT id FROM agent_handoffs WHERE status IN ('queued','claimed') AND expires_at IS NOT NULL AND expires_at<=unixepoch() ORDER BY expires_at LIMIT 100) AND status IN ('queued','claimed') AND expires_at<=unixepoch() RETURNING id")
            .fetch_all(&mut *tx)
            .await?;
            let batch_size = ids.len();
            for id in ids {
                let row = Self::handoff_in_tx(&mut tx, &id).await?;
                Self::handoff_event(&mut tx, &row, "timed_out").await?;
                Self::enqueue_result_delivery(&mut tx, &row).await?;
            }
            tx.commit().await?;
            total += batch_size;
            if batch_size < 100 {
                return Ok(total);
            }
        }
    }
    pub(super) async fn list_handoffs(
        &self,
        status: Option<&str>,
        before: Option<i64>,
        owner: bool,
    ) -> Result<Value> {
        if let Some(s) = status
            && ![
                "queued",
                "claimed",
                "completed",
                "failed",
                "cancelled",
                "timed_out",
            ]
            .contains(&s)
        {
            bail!("Invalid status");
        }
        self.expire_handoffs().await?;
        let before = before.unwrap_or(i64::MAX);
        if before < 1 {
            bail!("Invalid cursor");
        }
        let mut rows: Vec<Handoff> = if owner {
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE rowid<? AND (? IS NULL OR status=?) ORDER BY rowid DESC LIMIT 101")
                .bind(before).bind(status).bind(status).fetch_all(&self.0.db).await?
        } else {
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE rowid<? AND (sender_id=? OR recipient_id=?) AND (? IS NULL OR status=?) ORDER BY rowid DESC LIMIT 101")
                .bind(before).bind(self.connection_id()).bind(self.connection_id()).bind(status).bind(status).fetch_all(&self.0.db).await?
        };
        let next = if rows.len() > 100 {
            rows.truncate(100);
            rows.last().map(|row| row.cursor)
        } else {
            None
        };
        Ok(json!({"items":rows,"next":next}))
    }
    pub(super) async fn get_handoff(&self, id: &str, owner: bool) -> Result<Value> {
        self.expire_handoffs().await?;
        let row: Option<Handoff> =
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE id=?")
                .bind(id)
                .fetch_optional(&self.0.db)
                .await?;
        let row = row
            .filter(|r| {
                owner
                    || r.sender_id == self.connection_id()
                    || r.recipient_id == self.connection_id()
            })
            .ok_or_else(missing)?;
        Ok(serde_json::to_value(row)?)
    }
    async fn handoff_history(&self, id: &str, after: i64) -> Result<Value> {
        self.get_handoff(id, true).await?;
        if after < 0 {
            bail!("Invalid cursor");
        }
        let rows:Vec<(i64,String)>=sqlx::query_as("SELECT sequence,payload FROM events WHERE kind='agent.handoff' AND json_extract(payload,'$.id')=? AND sequence>? ORDER BY sequence LIMIT 101")
            .bind(id).bind(after).fetch_all(&self.0.db).await?;
        let has_more = rows.len() > 100;
        let mut items = Vec::new();
        for (sequence, payload) in rows.into_iter().take(100) {
            items
                .push(json!({"sequence":sequence,"task":serde_json::from_str::<Value>(&payload)?}));
        }
        let next = if has_more {
            items.last().and_then(|v| v["sequence"].as_i64())
        } else {
            None
        };
        Ok(json!({"items":items,"next":next}))
    }
    pub(super) async fn claim_handoff(&self, id: &str, token: &str) -> Result<Value> {
        if Uuid::parse_str(token)?.get_version_num() != 4 {
            bail!("claim_token must be a random UUID v4");
        }
        let hash = claim_digest(token);
        let _guard = self.0.mutation.lock().await;
        let mut tx = self.0.db.begin().await?;
        let prior: Option<Handoff> = sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE id=? AND recipient_id=? AND status='claimed' AND lease_until>=unixepoch() AND (expires_at IS NULL OR expires_at>unixepoch()) AND claim_hash=?")
            .bind(id).bind(self.connection_id()).bind(&hash).fetch_optional(&mut *tx).await?;
        if let Some(prior) = prior {
            let mut value = serde_json::to_value(prior)?;
            value["claim_token"] = json!(token);
            return Ok(value);
        }
        let changed = sqlx::query(
            "UPDATE agent_handoffs SET status='claimed',claim_hash=?,lease_until=unixepoch()+?,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND recipient_id=? AND (status='queued' OR (status='claimed' AND lease_until<unixepoch())) AND (expires_at IS NULL OR expires_at>unixepoch()) AND EXISTS(SELECT 1 FROM agent_connections WHERE id=? AND disconnected=0)")
            .bind(hash).bind(LEASE_SECONDS).bind(id).bind(self.connection_id()).bind(self.connection_id())
            .execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Task is not claimable"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, "claimed").await?;
        tx.commit().await?;
        let mut value = serde_json::to_value(row)?;
        value["claim_token"] = json!(token);
        Ok(value)
    }
    pub(super) async fn renew_handoff(&self, id: &str, token: &str) -> Result<Value> {
        let mut tx = self.0.db.begin().await?;
        let changed=sqlx::query("UPDATE agent_handoffs SET lease_until=unixepoch()+?,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND recipient_id=? AND status='claimed' AND lease_until>=unixepoch() AND (expires_at IS NULL OR expires_at>unixepoch()) AND claim_hash=?")
            .bind(LEASE_SECONDS).bind(id).bind(self.connection_id()).bind(claim_digest(token)).execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Claim expired or task is no longer active"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, "renewed").await?;
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
    pub(super) async fn finish_handoff(
        &self,
        id: &str,
        input: FinishInput,
        failed: bool,
    ) -> Result<Value> {
        if !valid_text(&input.message, 16_000) {
            bail!("Result is empty or too long");
        }
        let mut tx = self.0.db.begin().await?;
        let changed=sqlx::query("UPDATE agent_handoffs SET status=?,result=?,error=?,claim_hash=NULL,lease_until=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND recipient_id=? AND status='claimed' AND lease_until>=unixepoch() AND (expires_at IS NULL OR expires_at>unixepoch()) AND claim_hash=?")
            .bind(if failed {"failed"}else{"completed"})
            .bind(if failed {None}else{Some(input.message.as_str())})
            .bind(if failed {Some(input.message.as_str())}else{None})
            .bind(id).bind(self.connection_id()).bind(claim_digest(&input.claim_token)).execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Claim expired or task is no longer active"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, if failed { "failed" } else { "completed" }).await?;
        Self::enqueue_result_delivery(&mut tx, &row).await?;
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
    pub(super) async fn cancel_handoff(&self, id: &str) -> Result<Value> {
        self.expire_handoffs().await?;
        let mut tx = self.0.db.begin().await?;
        let changed=sqlx::query("UPDATE agent_handoffs SET status='cancelled',claim_hash=NULL,lease_until=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND sender_id=? AND status IN ('queued','claimed') AND (expires_at IS NULL OR expires_at>unixepoch())")
            .bind(id).bind(self.connection_id()).execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Task cannot be cancelled"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, "cancelled").await?;
        Self::enqueue_result_delivery(&mut tx, &row).await?;
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
    pub(super) async fn acknowledge_handoff_result(&self, id: &str) -> Result<Value> {
        self.expire_handoffs().await?;
        let _guard = self.0.mutation.lock().await;
        let mut tx = self.0.db.begin().await?;
        let changed = sqlx::query("UPDATE agent_handoffs SET result_acknowledged_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND sender_id=? AND status IN ('completed','failed','cancelled','timed_out') AND result_acknowledged_at IS NULL AND EXISTS(SELECT 1 FROM agent_connections WHERE id=? AND disconnected=0)")
            .bind(id).bind(self.connection_id()).bind(self.connection_id())
            .execute(&mut *tx).await?;
        let row: Option<Handoff> =
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE id=?")
                .bind(id)
                .fetch_optional(&mut *tx)
                .await?;
        let row = row.ok_or_else(missing)?;
        if row.sender_id != self.connection_id() {
            return Err(missing());
        }
        if changed.rows_affected() == 1 {
            Self::handoff_event(&mut tx, &row, "result_acknowledged").await?;
        } else if row.result_acknowledged_at.is_none() {
            return Err(conflict("Task has no result to acknowledge"));
        }
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
}
async fn agents(http::AgentState(p): http::AgentState) -> Api<Value> {
    Ok(Json(p.discover_agents().await?))
}
async fn create(
    http::AgentState(p): http::AgentState,
    Json(input): Json<CreateHandoff>,
) -> Api<Value> {
    Ok(Json(p.create_handoff(input).await?))
}
async fn list(http::AgentState(p): http::AgentState, Query(q): Query<ListQuery>) -> Api<Value> {
    Ok(Json(
        p.list_handoffs(q.status.as_deref(), q.before, false)
            .await?,
    ))
}
async fn read(http::AgentState(p): http::AgentState, Path(id): Path<String>) -> Api<Value> {
    Ok(Json(p.get_handoff(&id, false).await?))
}
async fn claim(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<ClaimInput>,
) -> Api<Value> {
    Ok(Json(p.claim_handoff(&id, &input.claim_token).await?))
}
async fn renew(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<ClaimInput>,
) -> Api<Value> {
    Ok(Json(p.renew_handoff(&id, &input.claim_token).await?))
}
async fn complete(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<FinishInput>,
) -> Api<Value> {
    Ok(Json(p.finish_handoff(&id, input, false).await?))
}
async fn fail(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<FinishInput>,
) -> Api<Value> {
    Ok(Json(p.finish_handoff(&id, input, true).await?))
}
async fn cancel(http::AgentState(p): http::AgentState, Path(id): Path<String>) -> Api<Value> {
    Ok(Json(p.cancel_handoff(&id).await?))
}
async fn ack_result(http::AgentState(p): http::AgentState, Path(id): Path<String>) -> Api<Value> {
    Ok(Json(p.acknowledge_handoff_result(&id).await?))
}
async fn owner_list(State(p): State<Publisher>, Query(q): Query<ListQuery>) -> Api<Value> {
    Ok(Json(
        p.list_handoffs(q.status.as_deref(), q.before, true).await?,
    ))
}
async fn owner_get(State(p): State<Publisher>, Path(id): Path<String>) -> Api<Value> {
    Ok(Json(p.get_handoff(&id, true).await?))
}
async fn owner_history(
    State(p): State<Publisher>,
    Path(id): Path<String>,
    Query(q): Query<HistoryQuery>,
) -> Api<Value> {
    Ok(Json(p.handoff_history(&id, q.after.unwrap_or(0)).await?))
}
#[derive(Serialize, FromRow)]
struct HandoffGrant {
    sender_id: String,
    recipient_id: String,
}
async fn all_grants(State(p): State<Publisher>) -> Api<Vec<HandoffGrant>> {
    let rows = sqlx::query_as(
        "SELECT sender_id, recipient_id FROM agent_handoff_grants ORDER BY sender_id, recipient_id",
    )
    .fetch_all(&p.0.db)
    .await?;
    Ok(Json(rows))
}
async fn grants(State(p): State<Publisher>, Path(sender_id): Path<String>) -> Api<Value> {
    let ids: Vec<String> = sqlx::query_scalar(
        "SELECT recipient_id FROM agent_handoff_grants WHERE sender_id=? ORDER BY recipient_id",
    )
    .bind(sender_id)
    .fetch_all(&p.0.db)
    .await?;
    Ok(Json(json!(ids)))
}
async fn set_grant(
    State(p): State<Publisher>,
    Path(sender_id): Path<String>,
    Json(input): Json<GrantInput>,
) -> Api<Value> {
    if sender_id == input.recipient_id {
        return Err(anyhow::anyhow!("An agent cannot assign work to itself").into());
    }
    let _guard = p.0.mutation.lock().await;
    if input.enabled {
        let count: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM agent_connections WHERE id IN (?,?) AND disconnected=0 AND last_seen IS NOT NULL",
        )
        .bind(&sender_id)
        .bind(&input.recipient_id)
        .fetch_one(&p.0.db)
        .await?;
        if count != 2 {
            return Err(anyhow::anyhow!("Both agents must be connected").into());
        }
        sqlx::query(
            "INSERT OR IGNORE INTO agent_handoff_grants(sender_id,recipient_id) VALUES(?,?)",
        )
        .bind(&sender_id)
        .bind(&input.recipient_id)
        .execute(&p.0.db)
        .await?;
    } else {
        sqlx::query("DELETE FROM agent_handoff_grants WHERE sender_id=? AND recipient_id=?")
            .bind(&sender_id)
            .bind(&input.recipient_id)
            .execute(&p.0.db)
            .await?;
    }
    drop(_guard);
    grants(State(p), Path(sender_id)).await
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn deadline_migration_preserves_existing_tasks_and_cursors() {
        let dir = tempfile::tempdir().unwrap();
        let options = sqlx::sqlite::SqliteConnectOptions::new()
            .filename(dir.path().join("legacy.db"))
            .create_if_missing(true);
        let db = sqlx::SqlitePool::connect_with(options).await.unwrap();
        sqlx::raw_sql("CREATE TABLE agent_connections(id TEXT PRIMARY KEY); CREATE TABLE events(sequence INTEGER PRIMARY KEY,kind TEXT,payload TEXT);")
            .execute(&db).await.unwrap();
        sqlx::raw_sql(include_str!(
            "../../../../migrations/0018_agent_handoffs.sql"
        ))
        .execute(&db)
        .await
        .unwrap();
        sqlx::raw_sql(include_str!(
            "../../../../migrations/0019_agent_handoff_result_receipts.sql"
        ))
        .execute(&db)
        .await
        .unwrap();
        sqlx::query("INSERT INTO agent_connections(id) VALUES('sender'),('receiver')")
            .execute(&db)
            .await
            .unwrap();
        sqlx::query("INSERT INTO agent_handoffs(id,request_id,sender_id,sender_name,recipient_id,recipient_name,title,instructions,status,result,result_acknowledged_at,revision) VALUES('old','request','sender','Muse','receiver','Grok','Legacy','Check','completed','Done','2026-09-23T00:00:00Z',4)")
            .execute(&db).await.unwrap();
        let cursor: i64 = sqlx::query_scalar("SELECT rowid FROM agent_handoffs WHERE id='old'")
            .fetch_one(&db)
            .await
            .unwrap();
        sqlx::raw_sql(include_str!(
            "../../../../migrations/0020_agent_handoff_deadlines.sql"
        ))
        .execute(&db)
        .await
        .unwrap();
        let row: (i64, String, String, i64, Option<i64>) = sqlx::query_as("SELECT rowid,result,result_acknowledged_at,revision,expires_at FROM agent_handoffs WHERE id='old'")
            .fetch_one(&db).await.unwrap();
        assert_eq!(
            row,
            (
                cursor,
                "Done".into(),
                "2026-09-23T00:00:00Z".into(),
                4,
                None
            )
        );
        sqlx::raw_sql(include_str!(
            "../../../../migrations/0021_handoff_delivery_foundation.sql"
        ))
        .execute(&db)
        .await
        .unwrap();
        let migrated: (i64, String, i64, Option<i64>) = sqlx::query_as(
            "SELECT rowid,delivery_mode,revision,sender_binding_generation FROM agent_handoffs WHERE id='old'",
        )
        .fetch_one(&db)
        .await
        .unwrap();
        assert_eq!(migrated, (cursor, "pull".into(), 4, None));
    }
    async fn fixture() -> (tempfile::TempDir, Publisher) {
        let dir = tempfile::tempdir().unwrap();
        let db = crate::database(&format!(
            "sqlite://{}",
            dir.path().join("test.db").display()
        ))
        .await
        .unwrap();
        let p = Publisher::new(db, dir.path().join("publishing"), CancellationToken::new())
            .await
            .unwrap();
        for (id, name) in [
            ("sender", "Muse"),
            ("receiver", "Grok"),
            ("stranger", "Claude"),
        ] {
            sqlx::query("INSERT INTO agent_connections(id,name,product,token,publish_enabled) VALUES(?,?,?,?,0)")
                .bind(id).bind(name).bind(name).bind("test-ciphertext").execute(&p.0.db).await.unwrap();
        }
        (dir, p)
    }
    #[tokio::test]
    async fn automatic_delivery_requires_two_current_bindings_and_commits_both_directions() {
        let (_dir, p) = fixture().await;
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        let sender = p.for_connection("sender");
        let receiver = p.for_connection("receiver");
        let request_id = Uuid::new_v4().to_string();
        let input = || CreateHandoff {
            request_id: request_id.clone(),
            recipient_id: "receiver".into(),
            title: "Probe".into(),
            instructions: "Confirm receipt".into(),
            timeout_seconds: Some(60),
            automatic_delivery: true,
        };
        assert!(sender.create_handoff(input()).await.is_err());
        let count: i64 = sqlx::query_scalar("SELECT count(*) FROM agent_handoffs")
            .fetch_one(&p.0.db)
            .await
            .unwrap();
        assert_eq!(count, 0);
        for (id, product, generation) in [("sender", "Muse", 2), ("receiver", "Grok", 3)] {
            sqlx::query("INSERT INTO handoff_receiver_bindings(connection_id,product,target_ciphertext,receiver_secret_hash,generation,enabled,verified_at,proof_expires_at) VALUES(?,?,?, ?,?,1,unixepoch(),unixepoch()+3600)")
                .bind(id).bind(product).bind("encrypted-test-target").bind("test-hash")
                .bind(generation).execute(&p.0.db).await.unwrap();
        }
        let created = sender.create_handoff(input()).await.unwrap();
        let id = created["id"].as_str().unwrap();
        assert_eq!(created["delivery_mode"], "automatic");
        assert_eq!(created["sender_binding_generation"], 2);
        assert_eq!(created["recipient_binding_generation"], 3);
        let offer: (String, String, i64) = sqlx::query_as("SELECT kind,connection_id,binding_generation FROM handoff_delivery_outbox WHERE task_id=?")
            .bind(id).fetch_one(&p.0.db).await.unwrap();
        assert_eq!(offer, ("task_offered".into(), "receiver".into(), 3));
        assert_eq!(sender.create_handoff(input()).await.unwrap(), created);
        assert!(
            sender
                .create_handoff(CreateHandoff {
                    automatic_delivery: false,
                    ..input()
                })
                .await
                .is_err()
        );
        let claim_token = Uuid::new_v4().to_string();
        receiver.claim_handoff(id, &claim_token).await.unwrap();
        receiver
            .finish_handoff(
                id,
                FinishInput {
                    claim_token,
                    message: "Done".into(),
                },
                false,
            )
            .await
            .unwrap();
        let deliveries: Vec<(String, String, i64)> = sqlx::query_as("SELECT kind,connection_id,binding_generation FROM handoff_delivery_outbox WHERE task_id=? ORDER BY kind")
            .bind(id).fetch_all(&p.0.db).await.unwrap();
        assert_eq!(
            deliveries,
            vec![
                ("result_available".into(), "sender".into(), 2),
                ("task_offered".into(), "receiver".into(), 3)
            ]
        );
    }

    #[tokio::test]
    async fn expired_binding_blocks_creation_and_timeout_enqueues_one_return() {
        let (_dir, p) = fixture().await;
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        for id in ["sender", "receiver"] {
            sqlx::query("INSERT INTO handoff_receiver_bindings(connection_id,product,target_ciphertext,receiver_secret_hash,generation,enabled,verified_at,proof_expires_at) VALUES(?,'test','cipher','hash',1,1,unixepoch(),unixepoch()+3600)")
                .bind(id).execute(&p.0.db).await.unwrap();
        }
        let sender = p.for_connection("sender");
        let input = || CreateHandoff {
            request_id: Uuid::new_v4().to_string(),
            recipient_id: "receiver".into(),
            title: "Probe".into(),
            instructions: "Check".into(),
            timeout_seconds: Some(60),
            automatic_delivery: true,
        };
        sqlx::query("UPDATE handoff_receiver_bindings SET verified_at=unixepoch()-7200,proof_expires_at=unixepoch()-1 WHERE connection_id='receiver'")
            .execute(&p.0.db).await.unwrap();
        assert!(sender.create_handoff(input()).await.is_err());
        sqlx::query("UPDATE handoff_receiver_bindings SET proof_expires_at=unixepoch()+3600 WHERE connection_id='receiver'")
            .execute(&p.0.db).await.unwrap();
        let created = sender.create_handoff(input()).await.unwrap();
        let id = created["id"].as_str().unwrap();
        sqlx::query("UPDATE agent_handoffs SET expires_at=unixepoch()-1 WHERE id=?")
            .bind(id)
            .execute(&p.0.db)
            .await
            .unwrap();
        assert_eq!(sender.expire_handoffs().await.unwrap(), 1);
        assert_eq!(sender.expire_handoffs().await.unwrap(), 0);
        let count: i64 = sqlx::query_scalar("SELECT count(*) FROM handoff_delivery_outbox WHERE task_id=? AND kind='result_available'")
            .bind(id).fetch_one(&p.0.db).await.unwrap();
        assert_eq!(count, 1);
    }
    #[tokio::test]
    async fn automatic_outbox_failure_rolls_back_task_and_event() {
        let (_dir, p) = fixture().await;
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        for id in ["sender", "receiver"] {
            sqlx::query("INSERT INTO handoff_receiver_bindings(connection_id,product,target_ciphertext,receiver_secret_hash,generation,enabled,verified_at,proof_expires_at) VALUES(?,'test','cipher','hash',1,1,unixepoch(),unixepoch()+3600)")
                .bind(id).execute(&p.0.db).await.unwrap();
        }
        sqlx::raw_sql("CREATE TRIGGER reject_offer BEFORE INSERT ON handoff_delivery_outbox WHEN NEW.kind='task_offered' BEGIN SELECT RAISE(ABORT, 'test outbox failure'); END;")
            .execute(&p.0.db).await.unwrap();
        let sender = p.for_connection("sender");
        let result = sender
            .create_handoff(CreateHandoff {
                request_id: Uuid::new_v4().to_string(),
                recipient_id: "receiver".into(),
                title: "Probe".into(),
                instructions: "Check".into(),
                timeout_seconds: Some(60),
                automatic_delivery: true,
            })
            .await;
        assert!(result.is_err());
        let task_count: i64 = sqlx::query_scalar("SELECT count(*) FROM agent_handoffs")
            .fetch_one(&p.0.db)
            .await
            .unwrap();
        let event_count: i64 =
            sqlx::query_scalar("SELECT count(*) FROM events WHERE kind='agent.handoff'")
                .fetch_one(&p.0.db)
                .await
                .unwrap();
        assert_eq!((task_count, event_count), (0, 0));
    }
    #[tokio::test]
    async fn permission_idempotency_claim_and_cancel() {
        let (_dir, p) = fixture().await;
        let sender = p.for_connection("sender");
        let receiver = p.for_connection("receiver");
        let stranger = p.for_connection("stranger");
        assert_eq!(sender.discover_agents().await.unwrap(), json!([]));
        let request_id = Uuid::new_v4().to_string();
        let input = || CreateHandoff {
            request_id: request_id.clone(),
            recipient_id: "receiver".into(),
            title: "Research".into(),
            instructions: "Review the facts".into(),
            timeout_seconds: None,
            automatic_delivery: false,
        };
        assert!(sender.create_handoff(input()).await.is_err());
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        let listed = all_grants(State(p.clone()))
            .await
            .ok()
            .expect("owner grant list")
            .0;
        assert_eq!(listed.len(), 1);
        assert_eq!(listed[0].sender_id, "sender");
        assert_eq!(listed[0].recipient_id, "receiver");
        assert_eq!(sender.discover_agents().await.unwrap()[0]["id"], "receiver");
        let created = sender.create_handoff(input()).await.unwrap();
        assert_eq!(created["delivery_mode"], "pull");
        let pull_deliveries: i64 =
            sqlx::query_scalar("SELECT count(*) FROM handoff_delivery_outbox WHERE task_id=?")
                .bind(created["id"].as_str().unwrap())
                .fetch_one(&p.0.db)
                .await
                .unwrap();
        assert_eq!(pull_deliveries, 0);
        assert!(
            sender
                .acknowledge_handoff_result(created["id"].as_str().unwrap())
                .await
                .is_err()
        );
        assert_eq!(sender.create_handoff(input()).await.unwrap(), created);
        assert_eq!(
            receiver
                .list_handoffs(Some("queued"), None, false)
                .await
                .unwrap()["items"][0]["id"],
            created["id"]
        );
        assert!(
            stranger
                .get_handoff(created["id"].as_str().unwrap(), false)
                .await
                .is_err()
        );
        assert!(
            stranger
                .claim_handoff(created["id"].as_str().unwrap(), &Uuid::new_v4().to_string())
                .await
                .is_err()
        );
        let id = created["id"].as_str().unwrap();
        let claim_token = Uuid::new_v4().to_string();
        let claim = receiver.claim_handoff(id, &claim_token).await.unwrap();
        assert_eq!(
            receiver.claim_handoff(id, &claim_token).await.unwrap(),
            claim
        );
        let token = claim["claim_token"].as_str().unwrap();
        assert!(
            sender
                .get_handoff(id, false)
                .await
                .unwrap()
                .get("claim_token")
                .is_none()
        );
        assert!(
            receiver
                .finish_handoff(
                    id,
                    FinishInput {
                        claim_token: "wrong".into(),
                        message: "Done".into()
                    },
                    false
                )
                .await
                .is_err()
        );
        sender.cancel_handoff(id).await.unwrap();
        assert!(
            receiver
                .finish_handoff(
                    id,
                    FinishInput {
                        claim_token: token.into(),
                        message: "Done".into()
                    },
                    false
                )
                .await
                .is_err()
        );
        assert_eq!(
            sender.get_handoff(id, false).await.unwrap()["status"],
            "cancelled"
        );
        receiver.disconnect_connection().await.unwrap();
        assert_eq!(sender.discover_agents().await.unwrap(), json!([]));
        assert!(
            all_grants(State(p))
                .await
                .ok()
                .expect("owner grant list after disconnect")
                .0
                .is_empty()
        );
    }
    #[tokio::test]
    async fn completion_is_durable_and_stale_claim_is_fenced() {
        let (_dir, p) = fixture().await;
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        let sender = p.for_connection("sender");
        let receiver = p.for_connection("receiver");
        let row = sender
            .create_handoff(CreateHandoff {
                request_id: Uuid::new_v4().to_string(),
                recipient_id: "receiver".into(),
                title: "Check".into(),
                instructions: "Check this".into(),
                timeout_seconds: None,
                automatic_delivery: false,
            })
            .await
            .unwrap();
        let id = row["id"].as_str().unwrap();
        let first = receiver
            .claim_handoff(id, &Uuid::new_v4().to_string())
            .await
            .unwrap();
        sqlx::query("UPDATE agent_handoffs SET lease_until=unixepoch()-1 WHERE id=?")
            .bind(id)
            .execute(&p.0.db)
            .await
            .unwrap();
        let second = receiver
            .claim_handoff(id, &Uuid::new_v4().to_string())
            .await
            .unwrap();
        assert_ne!(first["claim_token"], second["claim_token"]);
        assert!(
            receiver
                .finish_handoff(
                    id,
                    FinishInput {
                        claim_token: first["claim_token"].as_str().unwrap().into(),
                        message: "Late".into()
                    },
                    false
                )
                .await
                .is_err()
        );
        let done = receiver
            .finish_handoff(
                id,
                FinishInput {
                    claim_token: second["claim_token"].as_str().unwrap().into(),
                    message: "Verified".into(),
                },
                false,
            )
            .await
            .unwrap();
        assert_eq!(done["status"], "completed");
        assert!(done["result_acknowledged_at"].is_null());
        assert!(receiver.acknowledge_handoff_result(id).await.is_err());
        assert!(
            p.for_connection("stranger")
                .acknowledge_handoff_result(id)
                .await
                .is_err()
        );
        assert_eq!(
            sender.get_handoff(id, false).await.unwrap()["result"],
            "Verified"
        );
        let acknowledged = sender.acknowledge_handoff_result(id).await.unwrap();
        assert!(acknowledged["result_acknowledged_at"].is_string());
        assert_eq!(
            sender.acknowledge_handoff_result(id).await.unwrap(),
            acknowledged
        );
        let history = sender.handoff_history(id, 0).await.unwrap();
        assert_eq!(history["items"].as_array().unwrap().len(), 5);
        assert_eq!(history["items"][0]["task"]["action"], "created");
        assert_eq!(history["items"][3]["task"]["action"], "completed");
        assert_eq!(history["items"][4]["task"]["action"], "result_acknowledged");
        assert!(!history.to_string().contains("claim_token"));
        assert!(sender.cancel_handoff(id).await.is_err());
    }
    #[tokio::test]
    async fn deadline_is_terminal_audited_and_rejects_late_claims() {
        let (_dir, p) = fixture().await;
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        let sender = p.for_connection("sender");
        let recipient = p.for_connection("receiver");
        let request_id = Uuid::new_v4().to_string();
        let input = || CreateHandoff {
            request_id: request_id.clone(),
            recipient_id: "receiver".into(),
            title: "Probe".into(),
            instructions: "Check".into(),
            timeout_seconds: Some(60),
            automatic_delivery: false,
        };
        let created = sender.create_handoff(input()).await.unwrap();
        let id = created["id"].as_str().unwrap();
        assert_eq!(created["timeout_seconds"], 60);
        assert!(created["expires_at"].as_i64().unwrap() > 0);
        assert_eq!(sender.create_handoff(input()).await.unwrap(), created);
        assert!(
            sender
                .create_handoff(CreateHandoff {
                    timeout_seconds: Some(120),
                    ..input()
                })
                .await
                .is_err()
        );
        sqlx::query("UPDATE agent_handoffs SET expires_at=unixepoch()-1 WHERE id=?")
            .bind(id)
            .execute(&p.0.db)
            .await
            .unwrap();
        assert!(
            recipient
                .claim_handoff(id, &Uuid::new_v4().to_string())
                .await
                .is_err()
        );
        let (first, second) = tokio::join!(p.expire_handoffs(), p.expire_handoffs());
        assert_eq!(first.unwrap() + second.unwrap(), 1);
        let timed_out = sender.get_handoff(id, false).await.unwrap();
        assert_eq!(timed_out["status"], "timed_out");
        assert_eq!(timed_out["revision"], 2);
        assert!(
            timed_out["error"]
                .as_str()
                .unwrap()
                .contains("did not claim")
        );
        assert_eq!(p.expire_handoffs().await.unwrap(), 0);
        assert!(sender.cancel_handoff(id).await.is_err());
        assert_eq!(
            sender.create_handoff(input()).await.unwrap()["status"],
            "timed_out"
        );
        assert_eq!(
            sender.acknowledge_handoff_result(id).await.unwrap()["status"],
            "timed_out"
        );
        let history = sender.handoff_history(id, 0).await.unwrap();
        let actions: Vec<_> = history["items"]
            .as_array()
            .unwrap()
            .iter()
            .map(|item| item["task"]["action"].as_str().unwrap())
            .collect();
        assert_eq!(actions, ["created", "timed_out", "result_acknowledged"]);
    }
    #[tokio::test]
    async fn claimed_task_cannot_complete_after_deadline() {
        let (_dir, p) = fixture().await;
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        let sender = p.for_connection("sender");
        let recipient = p.for_connection("receiver");
        let created = sender
            .create_handoff(CreateHandoff {
                request_id: Uuid::new_v4().to_string(),
                recipient_id: "receiver".into(),
                title: "Probe".into(),
                instructions: "Check".into(),
                timeout_seconds: Some(60),
                automatic_delivery: false,
            })
            .await
            .unwrap();
        let id = created["id"].as_str().unwrap();
        let token = Uuid::new_v4().to_string();
        recipient.claim_handoff(id, &token).await.unwrap();
        sqlx::query("UPDATE agent_handoffs SET expires_at=unixepoch()-1 WHERE id=?")
            .bind(id)
            .execute(&p.0.db)
            .await
            .unwrap();
        assert!(recipient.renew_handoff(id, &token).await.is_err());
        assert!(
            recipient
                .finish_handoff(
                    id,
                    FinishInput {
                        claim_token: token,
                        message: "late".into()
                    },
                    false
                )
                .await
                .is_err()
        );
        assert_eq!(p.expire_handoffs().await.unwrap(), 1);
        let row = sender.get_handoff(id, false).await.unwrap();
        assert_eq!(row["status"], "timed_out");
        assert!(
            row["error"]
                .as_str()
                .unwrap()
                .contains("external effects may be unknown")
        );
        assert!(row["lease_until"].is_null());
    }
    #[tokio::test]
    async fn startup_worker_expires_abandoned_task_without_a_read() {
        let (_dir, p) = fixture().await;
        sqlx::query("INSERT INTO agent_handoffs(id,request_id,sender_id,sender_name,recipient_id,recipient_name,title,instructions,timeout_seconds,expires_at) VALUES('due','due-request','sender','Muse','receiver','Grok','Due','Check',60,unixepoch()-1)")
            .execute(&p.0.db).await.unwrap();
        let worker = p.start_worker();
        tokio::time::timeout(Duration::from_secs(3), async {
            loop {
                let status: String =
                    sqlx::query_scalar("SELECT status FROM agent_handoffs WHERE id='due'")
                        .fetch_one(&p.0.db)
                        .await
                        .unwrap();
                if status == "timed_out" {
                    break;
                }
                tokio::time::sleep(Duration::from_millis(20)).await;
            }
        })
        .await
        .expect("startup deadline sweep");
        p.0.shutdown.cancel();
        worker.await.unwrap();
        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM events WHERE kind='agent.handoff' AND json_extract(payload,'$.id')='due' AND json_extract(payload,'$.action')='timed_out'")
            .fetch_one(&p.0.db).await.unwrap();
        assert_eq!(count, 1);
    }
}
