//! Durable, permissioned agent-to-agent work. Delivery is an authenticated pull inbox.
use super::*;
use axum::http::StatusCode;
use axum::{
    Json, Router,
    extract::{Path, Query, State},
    routing::{get, post},
};
use sha2::{Digest, Sha256};

type Api<T> = std::result::Result<Json<T>, http::Error>;
const LEASE_SECONDS: i64 = 300;
#[derive(Debug)]
pub(super) struct HandoffError {
    pub status: StatusCode,
    pub message: &'static str,
}
impl std::fmt::Display for HandoffError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.message)
    }
}
impl std::error::Error for HandoffError {}
fn conflict(message: &'static str) -> anyhow::Error {
    HandoffError {
        status: StatusCode::CONFLICT,
        message,
    }
    .into()
}
fn forbidden(message: &'static str) -> anyhow::Error {
    HandoffError {
        status: StatusCode::FORBIDDEN,
        message,
    }
    .into()
}
fn missing() -> anyhow::Error {
    HandoffError {
        status: StatusCode::NOT_FOUND,
        message: "Task not found",
    }
    .into()
}

#[derive(Debug, Clone, Serialize, FromRow)]
pub(super) struct Handoff {
    pub cursor: i64,
    pub id: String,
    pub request_id: String,
    pub sender_id: String,
    pub sender_name: String,
    pub recipient_id: String,
    pub recipient_name: String,
    pub title: String,
    pub instructions: String,
    pub status: String,
    pub result: Option<String>,
    pub error: Option<String>,
    #[serde(skip_serializing)]
    #[sqlx(rename = "claim_hash")]
    _claim_hash: Option<String>,
    pub lease_until: Option<i64>,
    pub created_at: String,
    pub updated_at: String,
    pub revision: i64,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct CreateHandoff {
    /// Stable UUID; reuse it for retries of the same task.
    pub request_id: String,
    /// Stable ID from list_agents; the owner must permit this sender to assign work to it.
    pub recipient_id: String,
    pub title: String,
    pub instructions: String,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct ClaimInput {
    /// Random UUID generated by the recipient. Reuse for lost claim responses and renew/complete/fail.
    pub claim_token: String,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct FinishInput {
    pub claim_token: String,
    /// Result for completion, explanation for failure.
    pub message: String,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct TaskClaim {
    pub id: String,
    pub claim_token: String,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct TaskFinish {
    pub id: String,
    pub claim_token: String,
    pub message: String,
}
#[derive(Deserialize)]
struct ListQuery {
    status: Option<String>,
    before: Option<i64>,
}
#[derive(Deserialize)]
struct HistoryQuery {
    after: Option<i64>,
}
#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct ListHandoffs {
    pub status: Option<String>,
    /// Cursor returned in next by the previous page.
    pub before: Option<i64>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct GrantInput {
    recipient_id: String,
    enabled: bool,
}

pub(super) fn admin_routes() -> Router<Publisher> {
    Router::new()
        .route(
            "/api/agent-handoff-grants/{sender_id}",
            get(grants).post(set_grant),
        )
        .route("/api/agent-handoffs", get(owner_list))
        .route("/api/agent-handoffs/{id}", get(owner_get))
        .route("/api/agent-handoffs/{id}/history", get(owner_history))
}
pub(super) fn agent_routes() -> Router<Publisher> {
    Router::new()
        .route("/v1/agents", get(agents))
        .route("/v1/agent-tasks", get(list).post(create))
        .route("/v1/agent-tasks/{id}", get(read))
        .route("/v1/agent-tasks/{id}/claim", post(claim))
        .route("/v1/agent-tasks/{id}/renew", post(renew))
        .route("/v1/agent-tasks/{id}/complete", post(complete))
        .route("/v1/agent-tasks/{id}/fail", post(fail))
        .route("/v1/agent-tasks/{id}/cancel", post(cancel))
}
fn valid_text(value: &str, max: usize) -> bool {
    !value.trim().is_empty()
        && value.len() <= max
        && !value
            .chars()
            .any(|c| c.is_control() && c != '\n' && c != '\t')
}
fn claim_digest(token: &str) -> String {
    format!("{:x}", Sha256::digest(token.as_bytes()))
}

impl Publisher {
    pub(super) async fn discover_agents(&self) -> Result<Value> {
        let rows: Vec<(String, String, String)> = sqlx::query_as(
            "SELECT c.id,c.name,c.product FROM agent_handoff_grants g JOIN agent_connections c ON c.id=g.recipient_id WHERE g.sender_id=? AND c.disconnected=0 ORDER BY c.name,c.id")
            .bind(self.connection_id()).fetch_all(&self.0.db).await?;
        Ok(json!(rows.into_iter().map(|(id,name,product)| json!({"id":id,"name":name,"product":product,"delivery":"inbox"})).collect::<Vec<_>>()))
    }
    pub(super) async fn create_handoff(&self, input: CreateHandoff) -> Result<Value> {
        Uuid::parse_str(&input.request_id)?;
        if !valid_text(&input.title, 200) || !valid_text(&input.instructions, 16_000) {
            bail!("Task title or instructions are empty or too long");
        }
        if self.connection_id() == input.recipient_id {
            bail!("Choose another agent");
        }
        let _guard = self.0.mutation.lock().await;
        let mut tx = self.0.db.begin().await?;
        if let Some(existing) = sqlx::query_as::<_, Handoff>(
            "SELECT rowid AS cursor,* FROM agent_handoffs WHERE sender_id=? AND request_id=?",
        )
        .bind(self.connection_id())
        .bind(&input.request_id)
        .fetch_optional(&mut *tx)
        .await?
        {
            if existing.recipient_id != input.recipient_id
                || existing.title != input.title
                || existing.instructions != input.instructions
            {
                return Err(conflict("request_id already belongs to a different task"));
            }
            return Ok(serde_json::to_value(existing)?);
        }
        let sender: (String,) =
            sqlx::query_as("SELECT name FROM agent_connections WHERE id=? AND disconnected=0")
                .bind(self.connection_id())
                .fetch_one(&mut *tx)
                .await?;
        let recipient: Option<(String,)> = sqlx::query_as(
            "SELECT c.name FROM agent_handoff_grants g JOIN agent_connections c ON c.id=g.recipient_id WHERE g.sender_id=? AND g.recipient_id=? AND c.disconnected=0")
            .bind(self.connection_id()).bind(&input.recipient_id).fetch_optional(&mut *tx).await?;
        let recipient =
            recipient.ok_or_else(|| forbidden("Recipient is not available or permitted"))?;
        let id = Uuid::new_v4().to_string();
        sqlx::query("INSERT INTO agent_handoffs(id,request_id,sender_id,sender_name,recipient_id,recipient_name,title,instructions) VALUES(?,?,?,?,?,?,?,?)")
            .bind(&id).bind(&input.request_id).bind(self.connection_id()).bind(sender.0)
            .bind(&input.recipient_id).bind(recipient.0).bind(&input.title).bind(&input.instructions)
            .execute(&mut *tx).await?;
        let row = Self::handoff_in_tx(&mut tx, &id).await?;
        Self::handoff_event(&mut tx, &row, "created").await?;
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
    async fn handoff_in_tx(tx: &mut Transaction<'_, Sqlite>, id: &str) -> Result<Handoff> {
        Ok(
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE id=?")
                .bind(id)
                .fetch_one(&mut **tx)
                .await?,
        )
    }
    async fn handoff_event(
        tx: &mut Transaction<'_, Sqlite>,
        row: &Handoff,
        action: &str,
    ) -> Result<()> {
        let mut payload = serde_json::to_value(row)?;
        payload["action"] = json!(action);
        sqlx::query("INSERT INTO events(kind,payload) VALUES('agent.handoff',?)")
            .bind(payload.to_string())
            .execute(&mut **tx)
            .await?;
        Ok(())
    }
    pub(super) async fn list_handoffs(
        &self,
        status: Option<&str>,
        before: Option<i64>,
        owner: bool,
    ) -> Result<Value> {
        if let Some(s) = status
            && !["queued", "claimed", "completed", "failed", "cancelled"].contains(&s)
        {
            bail!("Invalid status");
        }
        let before = before.unwrap_or(i64::MAX);
        if before < 1 {
            bail!("Invalid cursor");
        }
        let mut rows: Vec<Handoff> = if owner {
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE rowid<? AND (? IS NULL OR status=?) ORDER BY rowid DESC LIMIT 101")
                .bind(before).bind(status).bind(status).fetch_all(&self.0.db).await?
        } else {
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE rowid<? AND (sender_id=? OR recipient_id=?) AND (? IS NULL OR status=?) ORDER BY rowid DESC LIMIT 101")
                .bind(before).bind(self.connection_id()).bind(self.connection_id()).bind(status).bind(status).fetch_all(&self.0.db).await?
        };
        let next = if rows.len() > 100 {
            rows.truncate(100);
            rows.last().map(|row| row.cursor)
        } else {
            None
        };
        Ok(json!({"items":rows,"next":next}))
    }
    pub(super) async fn get_handoff(&self, id: &str, owner: bool) -> Result<Value> {
        let row: Option<Handoff> =
            sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE id=?")
                .bind(id)
                .fetch_optional(&self.0.db)
                .await?;
        let row = row
            .filter(|r| {
                owner
                    || r.sender_id == self.connection_id()
                    || r.recipient_id == self.connection_id()
            })
            .ok_or_else(missing)?;
        Ok(serde_json::to_value(row)?)
    }
    async fn handoff_history(&self, id: &str, after: i64) -> Result<Value> {
        self.get_handoff(id, true).await?;
        if after < 0 {
            bail!("Invalid cursor");
        }
        let rows:Vec<(i64,String)>=sqlx::query_as("SELECT sequence,payload FROM events WHERE kind='agent.handoff' AND json_extract(payload,'$.id')=? AND sequence>? ORDER BY sequence LIMIT 101")
            .bind(id).bind(after).fetch_all(&self.0.db).await?;
        let has_more = rows.len() > 100;
        let mut items = Vec::new();
        for (sequence, payload) in rows.into_iter().take(100) {
            items
                .push(json!({"sequence":sequence,"task":serde_json::from_str::<Value>(&payload)?}));
        }
        let next = if has_more {
            items.last().and_then(|v| v["sequence"].as_i64())
        } else {
            None
        };
        Ok(json!({"items":items,"next":next}))
    }
    pub(super) async fn claim_handoff(&self, id: &str, token: &str) -> Result<Value> {
        if Uuid::parse_str(token)?.get_version_num() != 4 {
            bail!("claim_token must be a random UUID v4");
        }
        let hash = claim_digest(token);
        let _guard = self.0.mutation.lock().await;
        let mut tx = self.0.db.begin().await?;
        let prior: Option<Handoff> = sqlx::query_as("SELECT rowid AS cursor,* FROM agent_handoffs WHERE id=? AND recipient_id=? AND status='claimed' AND lease_until>=unixepoch() AND claim_hash=?")
            .bind(id).bind(self.connection_id()).bind(&hash).fetch_optional(&mut *tx).await?;
        if let Some(prior) = prior {
            let mut value = serde_json::to_value(prior)?;
            value["claim_token"] = json!(token);
            return Ok(value);
        }
        let changed = sqlx::query(
            "UPDATE agent_handoffs SET status='claimed',claim_hash=?,lease_until=unixepoch()+?,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND recipient_id=? AND (status='queued' OR (status='claimed' AND lease_until<unixepoch())) AND EXISTS(SELECT 1 FROM agent_connections WHERE id=? AND disconnected=0)")
            .bind(hash).bind(LEASE_SECONDS).bind(id).bind(self.connection_id()).bind(self.connection_id())
            .execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Task is not claimable"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, "claimed").await?;
        tx.commit().await?;
        let mut value = serde_json::to_value(row)?;
        value["claim_token"] = json!(token);
        Ok(value)
    }
    pub(super) async fn renew_handoff(&self, id: &str, token: &str) -> Result<Value> {
        let mut tx = self.0.db.begin().await?;
        let changed=sqlx::query("UPDATE agent_handoffs SET lease_until=unixepoch()+?,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND recipient_id=? AND status='claimed' AND lease_until>=unixepoch() AND claim_hash=?")
            .bind(LEASE_SECONDS).bind(id).bind(self.connection_id()).bind(claim_digest(token)).execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Claim expired or task is no longer active"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, "renewed").await?;
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
    pub(super) async fn finish_handoff(
        &self,
        id: &str,
        input: FinishInput,
        failed: bool,
    ) -> Result<Value> {
        if !valid_text(&input.message, 16_000) {
            bail!("Result is empty or too long");
        }
        let mut tx = self.0.db.begin().await?;
        let changed=sqlx::query("UPDATE agent_handoffs SET status=?,result=?,error=?,claim_hash=NULL,lease_until=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND recipient_id=? AND status='claimed' AND lease_until>=unixepoch() AND claim_hash=?")
            .bind(if failed {"failed"}else{"completed"})
            .bind(if failed {None}else{Some(input.message.as_str())})
            .bind(if failed {Some(input.message.as_str())}else{None})
            .bind(id).bind(self.connection_id()).bind(claim_digest(&input.claim_token)).execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Claim expired or task is no longer active"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, if failed { "failed" } else { "completed" }).await?;
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
    pub(super) async fn cancel_handoff(&self, id: &str) -> Result<Value> {
        let mut tx = self.0.db.begin().await?;
        let changed=sqlx::query("UPDATE agent_handoffs SET status='cancelled',claim_hash=NULL,lease_until=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),revision=revision+1 WHERE id=? AND sender_id=? AND status IN ('queued','claimed')")
            .bind(id).bind(self.connection_id()).execute(&mut *tx).await?;
        if changed.rows_affected() != 1 {
            return Err(conflict("Task cannot be cancelled"));
        }
        let row = Self::handoff_in_tx(&mut tx, id).await?;
        Self::handoff_event(&mut tx, &row, "cancelled").await?;
        tx.commit().await?;
        Ok(serde_json::to_value(row)?)
    }
}
async fn agents(http::AgentState(p): http::AgentState) -> Api<Value> {
    Ok(Json(p.discover_agents().await?))
}
async fn create(
    http::AgentState(p): http::AgentState,
    Json(input): Json<CreateHandoff>,
) -> Api<Value> {
    Ok(Json(p.create_handoff(input).await?))
}
async fn list(http::AgentState(p): http::AgentState, Query(q): Query<ListQuery>) -> Api<Value> {
    Ok(Json(
        p.list_handoffs(q.status.as_deref(), q.before, false)
            .await?,
    ))
}
async fn read(http::AgentState(p): http::AgentState, Path(id): Path<String>) -> Api<Value> {
    Ok(Json(p.get_handoff(&id, false).await?))
}
async fn claim(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<ClaimInput>,
) -> Api<Value> {
    Ok(Json(p.claim_handoff(&id, &input.claim_token).await?))
}
async fn renew(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<ClaimInput>,
) -> Api<Value> {
    Ok(Json(p.renew_handoff(&id, &input.claim_token).await?))
}
async fn complete(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<FinishInput>,
) -> Api<Value> {
    Ok(Json(p.finish_handoff(&id, input, false).await?))
}
async fn fail(
    http::AgentState(p): http::AgentState,
    Path(id): Path<String>,
    Json(input): Json<FinishInput>,
) -> Api<Value> {
    Ok(Json(p.finish_handoff(&id, input, true).await?))
}
async fn cancel(http::AgentState(p): http::AgentState, Path(id): Path<String>) -> Api<Value> {
    Ok(Json(p.cancel_handoff(&id).await?))
}
async fn owner_list(State(p): State<Publisher>, Query(q): Query<ListQuery>) -> Api<Value> {
    Ok(Json(
        p.list_handoffs(q.status.as_deref(), q.before, true).await?,
    ))
}
async fn owner_get(State(p): State<Publisher>, Path(id): Path<String>) -> Api<Value> {
    Ok(Json(p.get_handoff(&id, true).await?))
}
async fn owner_history(
    State(p): State<Publisher>,
    Path(id): Path<String>,
    Query(q): Query<HistoryQuery>,
) -> Api<Value> {
    Ok(Json(p.handoff_history(&id, q.after.unwrap_or(0)).await?))
}
async fn grants(State(p): State<Publisher>, Path(sender_id): Path<String>) -> Api<Value> {
    let ids: Vec<String> = sqlx::query_scalar(
        "SELECT recipient_id FROM agent_handoff_grants WHERE sender_id=? ORDER BY recipient_id",
    )
    .bind(sender_id)
    .fetch_all(&p.0.db)
    .await?;
    Ok(Json(json!(ids)))
}
async fn set_grant(
    State(p): State<Publisher>,
    Path(sender_id): Path<String>,
    Json(input): Json<GrantInput>,
) -> Api<Value> {
    if sender_id == input.recipient_id {
        return Err(anyhow::anyhow!("An agent cannot assign work to itself").into());
    }
    let _guard = p.0.mutation.lock().await;
    if input.enabled {
        let count: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM agent_connections WHERE id IN (?,?) AND disconnected=0 AND last_seen IS NOT NULL",
        )
        .bind(&sender_id)
        .bind(&input.recipient_id)
        .fetch_one(&p.0.db)
        .await?;
        if count != 2 {
            return Err(anyhow::anyhow!("Both agents must be connected").into());
        }
        sqlx::query(
            "INSERT OR IGNORE INTO agent_handoff_grants(sender_id,recipient_id) VALUES(?,?)",
        )
        .bind(&sender_id)
        .bind(&input.recipient_id)
        .execute(&p.0.db)
        .await?;
    } else {
        sqlx::query("DELETE FROM agent_handoff_grants WHERE sender_id=? AND recipient_id=?")
            .bind(&sender_id)
            .bind(&input.recipient_id)
            .execute(&p.0.db)
            .await?;
    }
    drop(_guard);
    grants(State(p), Path(sender_id)).await
}

#[cfg(test)]
mod tests {
    use super::*;
    async fn fixture() -> (tempfile::TempDir, Publisher) {
        let dir = tempfile::tempdir().unwrap();
        let db = crate::database(&format!(
            "sqlite://{}",
            dir.path().join("test.db").display()
        ))
        .await
        .unwrap();
        let p = Publisher::new(db, dir.path().join("publishing"), CancellationToken::new())
            .await
            .unwrap();
        for (id, name) in [
            ("sender", "Muse"),
            ("receiver", "Grok"),
            ("stranger", "Claude"),
        ] {
            sqlx::query("INSERT INTO agent_connections(id,name,product,token,publish_enabled) VALUES(?,?,?,?,0)")
                .bind(id).bind(name).bind(name).bind("test-ciphertext").execute(&p.0.db).await.unwrap();
        }
        (dir, p)
    }
    #[tokio::test]
    async fn permission_idempotency_claim_and_cancel() {
        let (_dir, p) = fixture().await;
        let sender = p.for_connection("sender");
        let receiver = p.for_connection("receiver");
        let stranger = p.for_connection("stranger");
        assert_eq!(sender.discover_agents().await.unwrap(), json!([]));
        let request_id = Uuid::new_v4().to_string();
        let input = || CreateHandoff {
            request_id: request_id.clone(),
            recipient_id: "receiver".into(),
            title: "Research".into(),
            instructions: "Review the facts".into(),
        };
        assert!(sender.create_handoff(input()).await.is_err());
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        assert_eq!(sender.discover_agents().await.unwrap()[0]["id"], "receiver");
        let created = sender.create_handoff(input()).await.unwrap();
        assert_eq!(sender.create_handoff(input()).await.unwrap(), created);
        assert_eq!(
            receiver
                .list_handoffs(Some("queued"), None, false)
                .await
                .unwrap()["items"][0]["id"],
            created["id"]
        );
        assert!(
            stranger
                .get_handoff(created["id"].as_str().unwrap(), false)
                .await
                .is_err()
        );
        assert!(
            stranger
                .claim_handoff(created["id"].as_str().unwrap(), &Uuid::new_v4().to_string())
                .await
                .is_err()
        );
        let id = created["id"].as_str().unwrap();
        let claim_token = Uuid::new_v4().to_string();
        let claim = receiver.claim_handoff(id, &claim_token).await.unwrap();
        assert_eq!(
            receiver.claim_handoff(id, &claim_token).await.unwrap(),
            claim
        );
        let token = claim["claim_token"].as_str().unwrap();
        assert!(
            sender
                .get_handoff(id, false)
                .await
                .unwrap()
                .get("claim_token")
                .is_none()
        );
        assert!(
            receiver
                .finish_handoff(
                    id,
                    FinishInput {
                        claim_token: "wrong".into(),
                        message: "Done".into()
                    },
                    false
                )
                .await
                .is_err()
        );
        sender.cancel_handoff(id).await.unwrap();
        assert!(
            receiver
                .finish_handoff(
                    id,
                    FinishInput {
                        claim_token: token.into(),
                        message: "Done".into()
                    },
                    false
                )
                .await
                .is_err()
        );
        assert_eq!(
            sender.get_handoff(id, false).await.unwrap()["status"],
            "cancelled"
        );
        receiver.disconnect_connection().await.unwrap();
        assert_eq!(sender.discover_agents().await.unwrap(), json!([]));
    }
    #[tokio::test]
    async fn completion_is_durable_and_stale_claim_is_fenced() {
        let (_dir, p) = fixture().await;
        sqlx::query(
            "INSERT INTO agent_handoff_grants(sender_id,recipient_id) VALUES('sender','receiver')",
        )
        .execute(&p.0.db)
        .await
        .unwrap();
        let sender = p.for_connection("sender");
        let receiver = p.for_connection("receiver");
        let row = sender
            .create_handoff(CreateHandoff {
                request_id: Uuid::new_v4().to_string(),
                recipient_id: "receiver".into(),
                title: "Check".into(),
                instructions: "Check this".into(),
            })
            .await
            .unwrap();
        let id = row["id"].as_str().unwrap();
        let first = receiver
            .claim_handoff(id, &Uuid::new_v4().to_string())
            .await
            .unwrap();
        sqlx::query("UPDATE agent_handoffs SET lease_until=unixepoch()-1 WHERE id=?")
            .bind(id)
            .execute(&p.0.db)
            .await
            .unwrap();
        let second = receiver
            .claim_handoff(id, &Uuid::new_v4().to_string())
            .await
            .unwrap();
        assert_ne!(first["claim_token"], second["claim_token"]);
        assert!(
            receiver
                .finish_handoff(
                    id,
                    FinishInput {
                        claim_token: first["claim_token"].as_str().unwrap().into(),
                        message: "Late".into()
                    },
                    false
                )
                .await
                .is_err()
        );
        let done = receiver
            .finish_handoff(
                id,
                FinishInput {
                    claim_token: second["claim_token"].as_str().unwrap().into(),
                    message: "Verified".into(),
                },
                false,
            )
            .await
            .unwrap();
        assert_eq!(done["status"], "completed");
        assert_eq!(
            sender.get_handoff(id, false).await.unwrap()["result"],
            "Verified"
        );
        let history = sender.handoff_history(id, 0).await.unwrap();
        assert_eq!(history["items"].as_array().unwrap().len(), 4);
        assert_eq!(history["items"][0]["task"]["action"], "created");
        assert_eq!(history["items"][3]["task"]["action"], "completed");
        assert!(!history.to_string().contains("claim_token"));
        assert!(sender.cancel_handoff(id).await.is_err());
    }
}
